### PR TITLE
Examples and additional language features.

### PR DESCRIPTION
**Pull request by shardulc**
This change is [Reviewable](https://reviewable.io/reviews/game-of-death/docs/4)

### CODE REVIEW

**Comment by aunali1** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[spec/lang/lang_egs, line 3 at r1](https://reviewable.io:443/reviews/game-of-death/docs/4#-KjsjW7aHmC7TGUc8gKI:-KjsjW7aHmC7TGUc8gKJ:bwofm8t) ([raw file](https://github.com/game-of-death/docs/blob/58e24e3be0e6cde526113d265bb07fcf03388136/spec/lang/lang_egs#L3)):*
> ```
> Examples of GoDlang as described in lang_spec:
> 
> Declarations and assignments:
> ```

Probably should use Markdown instead of this format.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/game-of-death/docs/4)*

**Comment by aunali1** [comment]
Also splitting up the examples into individual files would be useful.

**Comment by shardulc** [comment]
The examples file is a guide for writing the compiler and should not be considered official documentation. Official docs will use Markdown and have comprehensive examples in multiple files, but that is after we have a compiler working.

**Comment by aunali1** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/game-of-death/docs/4#-:-KjuOdJgvqksxRJB57sO:bnfp4nl)*

**Comment by mjuvekar7** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/game-of-death/docs/4#-:-KjxLtIUR_4R8JlZyL8S:bnfp4nl)*

**Comment by mjuvekar7** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/game-of-death/docs/4)*

**Comment by mjuvekar7** [comment]
Might want to allow slicing lists without a start or end index (for example `list[2:]` or `list[:3]`).

**Comment by shardulc** [comment]
Added those formats.

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/game-of-death/docs/4#-:-Kk1uPA_BAo8H-SHaAPH:brbgx56)*

**Comment by aunali1** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/game-of-death/docs/4#-:-Kk1v1EEwxwFF5K945Zc:bnfp4nl)*

**Pull request merged**
